name: Test and Release
on: [workflow_dispatch]
  
jobs:
 test-and-release:
  name: Run tests and release
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
    - name: Install dependencies
      run: npm i
    - name: Build
      run: npm build:all
    - name: Run tests
      run: npm test:all
    - name: Release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run semantic-release
