name: Test and Release
on: 
 pull_request:
   branches: [main]

jobs:
  test-and-release:
    name: Run tests and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
